# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IICAREdata Project
email: dtphelan1@gmail.com
description: >
 o enable clinical oncology research by prospectively gathering high quality real-world data. The ICAREdata project is a collaboration between MITRE, the Alliance for Clinical Trials in Oncology, and the Dana-Farber Cancer Institute.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Google services
google_analytics: UA-82650858-4

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - design
  - README.md
  - ideas

sass:
  sass_dir: _scss
  style: :compressed
